export const INITIAL_BOOKINGS = [
  {
    id: "BK-2025-001",
    customer: "Aria Patel",
    email: "aria.patel@email.com",
    initials: "AP",
    avatar: "bg-rose-100 text-rose-500",
    artist: "Sofia Chen",
    artistRole: "Bridal & Makeup",
    service: "Bridal Makeup",
    category: "Makeup",
    categoryColor: "text-fuchsia-500",
    date: "Jul 5, 2025",
    time: "10:00 AM",
    visitType: "Home",
    payment: "Paid",
    status: "Completed",
    amount: 4500,
  },
  {
    id: "BK-2025-002",
    customer: "Meera Singh",
    email: "meera.singh@email.com",
    initials: "MS",
    avatar: "bg-sky-100 text-sky-500",
    artist: "Priya Nair",
    artistRole: "Hair & Extensions",
    service: "Hair Spa Treatment",
    category: "Hair",
    categoryColor: "text-violet-500",
    date: "Jul 6, 2025",
    time: "2:00 PM",
    visitType: "Salon",
    payment: "Pending",
    status: "Pending",
    amount: 2800,
  },
  {
    id: "BK-2025-003",
    customer: "Kavya Reddy",
    email: "kavya.reddy@email.com",
    initials: "KR",
    avatar: "bg-amber-100 text-amber-600",
    artist: "Anita Sharma",
    artistRole: "Nail Art Specialist",
    service: "Nail Art & Pedicure",
    category: "Nails",
    categoryColor: "text-pink-500",
    date: "Jul 6, 2025",
    time: "11:00 AM",
    visitType: "Home",
    payment: "Paid",
    status: "Confirmed",
    amount: 1800,
  },
  {
    id: "BK-2025-004",
    customer: "Riya Jain",
    email: "riya.jain@email.com",
    initials: "RJ",
    avatar: "bg-rose-100 text-rose-500",
    artist: "Sofia Chen",
    artistRole: "Bridal & Makeup",
    service: "Party Makeup",
    category: "Makeup",
    categoryColor: "text-fuchsia-500",
    date: "Jul 7, 2025",
    time: "4:00 PM",
    visitType: "Salon",
    payment: "Paid",
    status: "In Progress",
    amount: 3200,
  },
  {
    id: "BK-2025-005",
    customer: "Nisha Gupta",
    email: "nisha.gupta@email.com",
    initials: "NG",
    avatar: "bg-emerald-100 text-emerald-600",
    artist: "Priya Nair",
    artistRole: "Hair & Extensions",
    service: "Keratin Treatment",
    category: "Hair",
    categoryColor: "text-violet-500",
    date: "Jul 8, 2025",
    time: "9:00 AM",
    visitType: "Home",
    payment: "Refunded",
    status: "Cancelled",
    amount: 6500,
  },
  {
    id: "BK-2025-006",
    customer: "Pooja Shah",
    email: "pooja.shah@email.com",
    initials: "PS",
    avatar: "bg-indigo-100 text-indigo-500",
    artist: "Anita Sharma",
    artistRole: "Nail Art Specialist",
    service: "Manicure + Spa",
    category: "Nails",
    categoryColor: "text-pink-500",
    date: "Jul 8, 2025",
    time: "1:00 PM",
    visitType: "Salon",
    payment: "Partial Refund",
    status: "Disputed",
    amount: 2400,
  },
  {
    id: "BK-2025-007",
    customer: "Tanya Verma",
    email: "tanya.verma@email.com",
    initials: "TV",
    avatar: "bg-cyan-100 text-cyan-600",
    artist: "Rekha Kumar",
    artistRole: "Skincare & Facials",
    service: "Anti-Aging Facial + C",
    category: "Skincare",
    categoryColor: "text-teal-500",
    date: "Jul 9, 2025",
    time: "5:00 PM",
    visitType: "Home",
    payment: "Paid",
    status: "Completed",
    amount: 3800,
  },
  {
    id: "BK-2025-008",
    customer: "Simran Kaur",
    email: "simran.kaur@email.com",
    initials: "SK",
    avatar: "bg-rose-100 text-rose-500",
    artist: "Sofia Chen",
    artistRole: "Bridal & Makeup",
    service: "Engagement Makeup",
    category: "Makeup",
    categoryColor: "text-fuchsia-500",
    date: "Jul 10, 2025",
    time: "8:00 AM",
    visitType: "Home",
    payment: "Pending",
    status: "Pending",
    amount: 7500,
  },
  {
    id: "BK-2025-009",
    customer: "Deepika Das",
    email: "deepika.das@email.com",
    initials: "DD",
    avatar: "bg-lime-100 text-lime-600",
    artist: "Rekha Kumar",
    artistRole: "Skincare & Facials",
    service: "Hair Color + Highlight",
    category: "Hair",
    categoryColor: "text-violet-500",
    date: "Jul 10, 2025",
    time: "12:00 PM",
    visitType: "Salon",
    payment: "Paid",
    status: "Confirmed",
    amount: 5200,
  },
  {
    id: "BK-2025-010",
    customer: "Ananya Roy",
    email: "ananya.roy@email.com",
    initials: "AR",
    avatar: "bg-orange-100 text-orange-500",
    artist: "Priya Nair",
    artistRole: "Hair & Extensions",
    service: "Bridal Mehndi",
    category: "Mehndi",
    categoryColor: "text-rose-500",
    date: "Jul 11, 2025",
    time: "10:00 AM",
    visitType: "Home",
    payment: "Partial Refund",
    status: "Disputed",
    amount: 8000,
  },
];
