import { VerificationDetail } from "./page";

export const VERIFICATION_DETAILS: Record<string, VerificationDetail> = {
  "VF-3301": {
    id: "VF-3301",
    name: "Priya Sharma",
    email: "priya.sharma@beauty.com",
    phone: "+61 445 678 901",
    initials: "PS",
    avatar: "/assets/verification/pic1.jpg",
    businessName: "Priya Beauty Studio",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 556",
    category: "Makeup Artist",
    experience: "7 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 556",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jun 28, 2026",
    verificationStatus: "Pending",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3302": {
    id: "VF-3302",
    name: "Isabella Romano",
    email: "isabella.r@hairpro.com.au",
    phone: "+61 467 890 123",
    initials: "IR",
    avatar: "/assets/verification/pic2.jpg",
    businessName: "Romano Hair & Style",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 556",
    category: "Hair Stylist",
    experience: "5 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 556",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jun 29, 2026",
    verificationStatus: "Under Review",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3303": {
    id: "VF-3303",
    name: "Mei Lin Chen",
    email: "meilin.chen@nailsbymei.com",
    phone: "+61 489 012 345",
    initials: "ML",
    avatar: "/assets/verification/pic3.jpg",
    businessName: "Mei's Nail Atelier",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 556",
    category: "Nail Technician",
    experience: "6 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 556",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jun 30, 2026",
    verificationStatus: "Pending",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: true },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3304": {
    id: "VF-3304",
    name: "Aisha Okonkwo",
    email: "aisha.ok@lashart.com.au",
    phone: "+61 412 903 456",
    initials: "AO",
    avatar: "/assets/verification/pic1.jpg",
    businessName: "Aisha Lash & Brow",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 556",
    category: "Lash Artist",
    experience: "4 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 556",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 1, 2026",
    verificationStatus: "Pending",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: true },
      { label: "Insurance Verified", completed: true },
    ],
  },
  "VF-3305": {
    id: "VF-3305",
    name: "Hannah Davis",
    email: "hannah.davis@beautypro.com",
    phone: "+61 412 903 457",
    initials: "HD",
    avatar: "/assets/verification/pic2.jpg",
    businessName: "Hannah Beauty Pro",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 558",
    category: "Makeup Artist",
    experience: "6 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 558",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 14, 2026",
    verificationStatus: "Rejected",
    statusColor: "text-destructive",
    statusBg: "bg-[#FBE2E2]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: false },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3306": {
    id: "VF-3306",
    name: "Emily Wilson",
    email: "emily.wilson@haircare.com",
    phone: "+61 412 903 458",
    initials: "EW",
    avatar: "/assets/verification/pic3.jpg",
    businessName: "Emily Hair Boutique",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 559",
    category: "Hair Stylist",
    experience: "8 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 559",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 15, 2026",
    verificationStatus: "Pending",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3307": {
    id: "VF-3307",
    name: "Zoe Anderson",
    email: "zoe.anderson@nailstudio.com",
    phone: "+61 412 903 459",
    initials: "ZA",
    avatar: "/assets/verification/pic1.jpg",
    businessName: "Zoe Nail Atelier",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 560",
    category: "Nail Technician",
    experience: "5 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 560",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 16, 2026",
    verificationStatus: "Approved",
    statusColor: "text-success",
    statusBg: "bg-[#DDF3E7]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: true },
      { label: "Insurance Verified", completed: true },
    ],
  },

  "VF-3308": {
    id: "VF-3308",
    name: "Ruby Evans",
    email: "ruby.evans@lashworld.com",
    phone: "+61 412 903 460",
    initials: "RE",
    avatar: "/assets/verification/pic2.jpg",
    businessName: "Ruby Lash World",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 561",
    category: "Lash Artist",
    experience: "4 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 561",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 17, 2026",
    verificationStatus: "Under Review",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },
  "VF-3309": {
    id: "VF-3309",
    name: "Charlotte Smith",
    email: "charlotte.smith@beautylab.com",
    phone: "+61 412 903 461",
    initials: "CS",
    avatar: "/assets/verification/pic3.jpg",
    businessName: "Charlotte Beauty Lab",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 562",
    category: "Makeup Artist",
    experience: "9 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 562",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 18, 2026",
    verificationStatus: "Pending",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3310": {
    id: "VF-3310",
    name: "Grace Taylor",
    email: "grace.taylor@hairpro.com",
    phone: "+61 412 903 462",
    initials: "GT",
    avatar: "/assets/verification/pic1.jpg",
    businessName: "Grace Hair Pro",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 563",
    category: "Hair Stylist",
    experience: "7 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 563",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 19, 2026",
    verificationStatus: "Approved",
    statusColor: "text-success",
    statusBg: "bg-[#DDF3E7]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: true },
      { label: "Insurance Verified", completed: true },
    ],
  },

  "VF-3311": {
    id: "VF-3311",
    name: "Maya Patel",
    email: "maya.patel@nailsbeauty.com",
    phone: "+61 412 903 463",
    initials: "MP",
    avatar: "/assets/verification/pic2.jpg",
    businessName: "Maya Nail Studio",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 564",
    category: "Nail Technician",
    experience: "6 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 564",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 20, 2026",
    verificationStatus: "Pending",
    statusColor: "text-warning",
    statusBg: "bg-[#FBF0D6]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: true },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },

  "VF-3312": {
    id: "VF-3312",
    name: "Ava Johnson",
    email: "ava.johnson@lashart.com",
    phone: "+61 412 903 464",
    initials: "AJ",
    avatar: "/assets/verification/pic3.jpg",
    businessName: "Ava Lash Art",
    businessAddress: "42 Collins St, Melbourne VIC 3000",
    abn: "51 824 753 565",
    category: "Lash Artist",
    experience: "5 years",
    businessRegistration: "Registered",
    registrationStatus: "Active",
    abuStatus: "Active - 51 824 753 565",
    insuranceType: "Public Liability - $10M",
    insuranceStatus: "Active",
    submittedAt: "Jul 21, 2026",
    verificationStatus: "Rejected",
    statusColor: "text-destructive",
    statusBg: "bg-[#FBE2E2]",
    documents: [
      {
        id: 1,
        title: "Driver Licence Front",
        image: "/assets/verification/pic2.jpg",
      },
      {
        id: 2,
        title: "Driver Licence Back",
        image: "/assets/verification/pic3.jpg",
      },
      {
        id: 3,
        title: "Selfie Verification",
        image: "/assets/verification/pic1.jpg",
      },
    ],
    certificates: [],
    verificationChecklist: [
      { label: "ID Verification", completed: true },
      { label: "Selfie Match", completed: true },
      { label: "ABN Check", completed: false },
      { label: "Certificates Review", completed: false },
      { label: "Insurance Verified", completed: false },
    ],
  },
};