export const VERIFICATION_REQUESTS = [
  // Existing VF-3301 to VF-3312 remain same

  {
    id: "VF-3313",
    name: "Sophie Miller",
    email: "sophie.miller@glambeauty.com",
    initials: "SM",
    businessName: "Sophie Glam Beauty",
    category: "Makeup Artist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 10, 2026",
    status: "Pending",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3314",
    name: "Isabella Taylor",
    email: "isabella.taylor@hairlux.com",
    initials: "IT",
    businessName: "Taylor Hair Studio",
    category: "Hair Stylist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 11, 2026",
    status: "Approved",
    statusVariant: "success" as const,
  },

  {
    id: "VF-3315",
    name: "Amara Joseph",
    email: "amara.joseph@nailart.com",
    initials: "AJ",
    businessName: "Amara Nail Lounge",
    category: "Nail Technician",
    categoryColor: "text-warning",
    categoryBg: "bg-[#FBF0D6]",
    submitted: "Jul 12, 2026",
    status: "Under Review",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3316",
    name: "Lily Thompson",
    email: "lily.thompson@lashbeauty.com",
    initials: "LT",
    businessName: "Lily Lash Studio",
    category: "Lash Artist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 13, 2026",
    status: "Pending",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3317",
    name: "Hannah Davis",
    email: "hannah.davis@beautypro.com",
    initials: "HD",
    businessName: "Hannah Beauty Pro",
    category: "Makeup Artist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 14, 2026",
    status: "Rejected",
    statusVariant: "danger" as const,
  },

  {
    id: "VF-3318",
    name: "Emily Wilson",
    email: "emily.wilson@haircare.com",
    initials: "EW",
    businessName: "Emily Hair Boutique",
    category: "Hair Stylist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 15, 2026",
    status: "Pending",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3319",
    name: "Zoe Anderson",
    email: "zoe.anderson@nailstudio.com",
    initials: "ZA",
    businessName: "Zoe Nail Atelier",
    category: "Nail Technician",
    categoryColor: "text-warning",
    categoryBg: "bg-[#FBF0D6]",
    submitted: "Jul 16, 2026",
    status: "Approved",
    statusVariant: "success" as const,
  },

  {
    id: "VF-3320",
    name: "Ruby Evans",
    email: "ruby.evans@lashworld.com",
    initials: "RE",
    businessName: "Ruby Lash World",
    category: "Lash Artist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 17, 2026",
    status: "Under Review",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3321",
    name: "Charlotte Smith",
    email: "charlotte.smith@beautylab.com",
    initials: "CS",
    businessName: "Charlotte Beauty Lab",
    category: "Makeup Artist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 18, 2026",
    status: "Pending",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3322",
    name: "Grace Taylor",
    email: "grace.taylor@hairpro.com",
    initials: "GT",
    businessName: "Grace Hair Pro",
    category: "Hair Stylist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 19, 2026",
    status: "Approved",
    statusVariant: "success" as const,
  },

  {
    id: "VF-3323",
    name: "Maya Patel",
    email: "maya.patel@nailsbeauty.com",
    initials: "MP",
    businessName: "Maya Nail Studio",
    category: "Nail Technician",
    categoryColor: "text-warning",
    categoryBg: "bg-[#FBF0D6]",
    submitted: "Jul 20, 2026",
    status: "Pending",
    statusVariant: "warning" as const,
  },

  {
    id: "VF-3324",
    name: "Ava Johnson",
    email: "ava.johnson@lashart.com",
    initials: "AJ",
    businessName: "Ava Lash Art",
    category: "Lash Artist",
    categoryColor: "text-brand-pinkDeep",
    categoryBg: "bg-[#FBE2E9]",
    submitted: "Jul 21, 2026",
    status: "Rejected",
    statusVariant: "danger" as const,
  },
];