export const notifications = [
  {
    id: 1,
    title: "New refund request",
    message: "Customer requested a refund for booking BK-2025-015",
    time: "5 minutes ago",
    unread: true,
  },
  {
    id: 2,
    title: "Booking cancelled",
    message: "Booking BK-2025-012 has been cancelled by the customer",
    time: "1 hour ago",
    unread: true,
  },
  {
    id: 3,
    title: "Payment completed",
    message: "Refund payment for booking BK-2025-008 has been processed successfully",
    time: "Yesterday",
    unread: false,
  },
  {
    id: 4,
    title: "New booking received",
    message: "A new booking request has been placed for Beauty Service appointment BK-2025-016",
    time: "10 minutes ago",
    unread: true,
  },
  {
    id: 5,
    title: "Provider verification completed",
    message: "Service provider Sarah Williams has completed verification successfully",
    time: "30 minutes ago",
    unread: true,
  },
  {
    id: 6,
    title: "New customer registered",
    message: "A new customer, Emma Johnson, created an account on the platform",
    time: "2 hours ago",
    unread: false,
  },
  {
    id: 7,
    title: "Payment received",
    message: "Payment of $120.00 has been received for booking BK-2025-014",
    time: "3 hours ago",
    unread: false,
  },
  {
    id: 8,
    title: "Booking completed",
    message: "Booking BK-2025-009 has been marked as completed",
    time: "Today",
    unread: false,
  },
  {
    id: 9,
    title: "Refund approved",
    message: "Refund request for booking BK-2025-010 has been approved by admin",
    time: "Yesterday",
    unread: true,
  },
  {
    id: 10,
    title: "New review received",
    message: "Customer left a 5-star review for Beauty Service booking BK-2025-011",
    time: "Yesterday",
    unread: false,
  },
  {
    id: 11,
    title: "Service provider updated profile",
    message: "John Smith updated availability and service pricing details",
    time: "2 days ago",
    unread: false,
  },
  {
    id: 12,
    title: "System maintenance scheduled",
    message: "Scheduled maintenance will occur on Sunday at 2:00 AM",
    time: "2 days ago",
    unread: false,
  },
  {
    id: 13,
    title: "Failed payment attempt",
    message: "Payment attempt failed for booking BK-2025-017. Customer needs to retry.",
    time: "3 days ago",
    unread: true,
  },
  {
    id: 14,
    title: "New support ticket created",
    message: "Customer submitted a support request regarding booking BK-2025-013",
    time: "3 days ago",
    unread: false,
  },
  {
    id: 15,
    title: "Monthly report generated",
    message: "Your monthly booking and revenue report is ready to view",
    time: "1 week ago",
    unread: false,
  },
];